<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Prueba el comercio</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <?= $employee->name ?>
                                <a href="/" class="btn btn-info float-right">Volver</a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Email</h5>
                                <p class="card-text"><?= $employee->email ?></p>

                                <h5 class="card-title">Phone</h5>
                                <p class="card-text"><?= $employee->phone ?></p>

                                <h5 class="card-title">Address</h5>
                                <p class="card-text"><?= $employee->address ?></p>

                                <h5 class="card-title">Position</h5>
                                <p class="card-text"><?= $employee->position ?></p>

                                <h5 class="card-title">Position</h5>
                                <p class="card-text"><?= $employee->position ?></p>

                                <h5 class="card-title">Salary</h5>
                                <p class="card-text"><?= $employee->salary ?></p>

                                <h5 class="card-title">Skills</h5>

                                <ul class="list-group list-group-flush">
                                    <?php foreach ($employee->skills as $skill) { ?>
                                        <li class="list-group-item"><?= $skill->skill ?></li>
                                    <?php }?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

